In [1]:
import pandas as pd
import numpy as np
import json
import os
import requests
import warnings
warnings.filterwarnings('ignore')

### Match List

#### Configuring API Call

In [ ]:
URL = "https://api.cricapi.com/v1/series_info"
APIKey = os.environ['APIKey']
OFFSET = "0"
SERIESId = "d5a498c8-7596-4b93-8ab0-e0efc3345312"
queryRequest = URL + "?apikey=" + APIKey + "&offset=" + OFFSET + "&id=" + SERIESId

# Checking Response Code
response = requests.get(queryRequest)

In [3]:
response

#### Loading Data

In [4]:
# Loading Data
data = json.loads(response.text)

In [5]:
data['info']

{'hitsToday': 2,
 'hitsUsed': 1,
 'hitsLimit': 100,
 'credits': 0,
 'server': 5,
 'queryTime': 76.9403,
 's': 0,
 'cache': 0}

In [71]:
# Getting Matches List into dataframe
match_list = pd.DataFrame.from_records(data['data']['matchList'])
match_list.head()

,id,name,matchType,status,venue,date,dateTimeGMT,teams,teamInfo,fantasyEnabled,bbbEnabled,hasSquad,matchStarted,matchEnded
0,208d68e5-3fab-4f3b-88e9-29ec4a02d3e2,"Chennai Super Kings vs Mumbai Indians, 3rd Match",t20,Chennai Super Kings won by 4 wkts,"MA Chidambaram Stadium, Chennai",2025-03-23,2025-03-23T14:00:00,"[Chennai Super Kings, Mumbai Indians]","[{'name': 'Chennai Super Kings', 'shortname': ...",True,True,True,True,True
1,83d70527-5fc4-4fad-8dd2-b88b385f379e,"Gujarat Titans vs Punjab Kings, 5th Match",t20,Punjab Kings won by 11 runs,"Narendra Modi Stadium, Ahmedabad",2025-03-25,2025-03-25T14:00:00,"[Gujarat Titans, Punjab Kings]","[{'name': 'Gujarat Titans', 'shortname': 'GT',...",True,True,True,True,True
2,d5915da0-c08b-4122-bcb0-2c2e1e6e168a,"Kolkata Knight Riders vs Sunrisers Hyderabad, ...",t20,Kolkata Knight Riders won by 80 runs,"Eden Gardens, Kolkata",2025-04-03,2025-04-03T14:00:00,"[Kolkata Knight Riders, Sunrisers Hyderabad]","[{'name': 'Kolkata Knight Riders', 'shortname'...",True,True,True,True,True
3,0a5ebe67-67a3-41d2-bbc8-5fc94aef0529,"Mumbai Indians vs Royal Challengers Bengaluru,...",t20,Royal Challengers Bengaluru won by 12 runs,"Wankhede Stadium, Mumbai",2025-04-07,2025-04-07T14:00:00,"[Mumbai Indians, Royal Challengers Bengaluru]","[{'name': 'Mumbai Indians', 'shortname': 'MI',...",True,True,True,True,True
4,56a88e0e-e844-41bd-ba65-3c905e36ba0d,"Punjab Kings vs Chennai Super Kings, 22nd Match",t20,Punjab Kings won by 18 runs,Maharaja Yadavindra Singh International Cricke...,2025-04-08,2025-04-08T14:00:00,"[Punjab Kings, Chennai Super Kings]","[{'name': 'Chennai Super Kings', 'shortname': ...",True,True,True,True,True

#### Data Cleaning

##### Keeping required columns

In [72]:
match_list = match_list[['id', 'name', 'matchType', 'venue', 'date', 'dateTimeGMT', 'matchStarted', 'matchEnded']]

In [73]:
match_list.head()

,id,name,matchType,venue,date,dateTimeGMT,matchStarted,matchEnded
0,208d68e5-3fab-4f3b-88e9-29ec4a02d3e2,"Chennai Super Kings vs Mumbai Indians, 3rd Match",t20,"MA Chidambaram Stadium, Chennai",2025-03-23,2025-03-23T14:00:00,True,True
1,83d70527-5fc4-4fad-8dd2-b88b385f379e,"Gujarat Titans vs Punjab Kings, 5th Match",t20,"Narendra Modi Stadium, Ahmedabad",2025-03-25,2025-03-25T14:00:00,True,True
2,d5915da0-c08b-4122-bcb0-2c2e1e6e168a,"Kolkata Knight Riders vs Sunrisers Hyderabad, ...",t20,"Eden Gardens, Kolkata",2025-04-03,2025-04-03T14:00:00,True,True
3,0a5ebe67-67a3-41d2-bbc8-5fc94aef0529,"Mumbai Indians vs Royal Challengers Bengaluru,...",t20,"Wankhede Stadium, Mumbai",2025-04-07,2025-04-07T14:00:00,True,True
4,56a88e0e-e844-41bd-ba65-3c905e36ba0d,"Punjab Kings vs Chennai Super Kings, 22nd Match",t20,Maharaja Yadavindra Singh International Cricke...,2025-04-08,2025-04-08T14:00:00,True,True

##### Processing Match Name and Match Numbers

In [74]:
match_list['MatchNumber'] = match_list.name.str.split(', ').str[1]
match_list.name = match_list.name.str.split(', ').str[0]
match_list['MatchNumber'].unique()

array(['3rd Match', '5th Match', '15th Match', '20th Match', '22nd Match',
       '24th Match', '25th Match', '26th Match', '27th Match',
       '28th Match', '21st Match', '19th Match', '44th Match',
       '1st Match', '11th Match', '12th Match', '2nd Match', '4th Match',
       '6th Match', '9th Match', '10th Match', '13th Match', '14th Match',
       '17th Match', '18th Match', '29th Match', '30th Match',
       '31st Match', '32nd Match', '33rd Match', '34th Match',
       '35th Match', '36th Match', '37th Match', '38th Match',
       '39th Match', '40th Match', '41st Match', '42nd Match',
       '43rd Match', '45th Match', '46th Match', '47th Match',
       '48th Match', '49th Match', '50th Match', '51st Match',
       '52nd Match', '53rd Match', '54th Match', '55th Match',
       '56th Match', '57th Match', 'No result', '58th Match',
       '60th Match', '59th Match', '61st Match', '62nd Match',
       '63rd Match', '64th Match', '65th Match', '66th Match',
       '68th Match', '67th Match', '69th Match', '70th Match',
       'Qualifier 1', 'Eliminator', 'Qualifier 2', 'Final', '16th Match',
       '23rd Match', '7th Match', '8th Match'], dtype=object)

In [75]:
match_list.MatchNumber.replace({
    'Qualifier 1': '71st Match',
    'Eliminator': '72nd Match',
    'Qualifier 2': '73rd Match',
    'Final': '74th Match'
}, inplace=True)

In [76]:
match_list.drop(match_list.loc[match_list.MatchNumber == 'No result'].index, inplace=True)

In [77]:
match_list.MatchNumber = match_list['MatchNumber'].str.extract(r'(\d+)', expand=False)

In [78]:
match_list.MatchNumber= match_list.MatchNumber.astype('int64')

In [79]:
match_list

,id,name,matchType,venue,date,dateTimeGMT,matchStarted,matchEnded,MatchNumber
0,208d68e5-3fab-4f3b-88e9-29ec4a02d3e2,Chennai Super Kings vs Mumbai Indians,t20,"MA Chidambaram Stadium, Chennai",2025-03-23,2025-03-23T14:00:00,True,True,3
1,83d70527-5fc4-4fad-8dd2-b88b385f379e,Gujarat Titans vs Punjab Kings,t20,"Narendra Modi Stadium, Ahmedabad",2025-03-25,2025-03-25T14:00:00,True,True,5
2,d5915da0-c08b-4122-bcb0-2c2e1e6e168a,Kolkata Knight Riders vs Sunrisers Hyderabad,t20,"Eden Gardens, Kolkata",2025-04-03,2025-04-03T14:00:00,True,True,15
3,0a5ebe67-67a3-41d2-bbc8-5fc94aef0529,Mumbai Indians vs Royal Challengers Bengaluru,t20,"Wankhede Stadium, Mumbai",2025-04-07,2025-04-07T14:00:00,True,True,20
4,56a88e0e-e844-41bd-ba65-3c905e36ba0d,Punjab Kings vs Chennai Super Kings,t20,Maharaja Yadavindra Singh International Cricke...,2025-04-08,2025-04-08T14:00:00,True,True,22
...,...,...,...,...,...,...,...,...,...
70,38f4d432-1349-4223-87ab-b1279c553754,Royal Challengers Bengaluru vs Punjab Kings,t20,"Narendra Modi Stadium, Ahmedabad",2025-06-03,2025-06-03T14:00:00,True,True,74
71,5dc7a22f-5057-4895-bb98-965d9a1f004e,Lucknow Super Giants vs Mumbai Indians,t20,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,2025-04-04,2025-04-04T14:00:00,True,True,16
72,71213f27-c274-48b0-97f7-ec74e895dcbe,Gujarat Titans vs Rajasthan Royals,t20,"Narendra Modi Stadium, Ahmedabad",2025-04-09,2025-04-09T14:00:00,True,True,23
73,ab4e0813-1e78-467e-aca0-d80c5cfe7dbd,Sunrisers Hyderabad vs Lucknow Super Giants,t20,"Rajiv Gandhi International Stadium, Hyderabad",2025-03-27,2025-03-27T14:00:00,True,True,7
74,7431523f-7ccb-4a4a-aed7-5c42fc08464c,Chennai Super Kings vs Royal Challengers Benga...,t20,"MA Chidambaram Stadium, Chennai",2025-03-28,2025-03-28T14:00:00,True,True,8

##### Renaming Columns

In [80]:
# Renaming Columns

match_list.rename(columns={
    'id': 'MatchID',
    'name': 'MatchName',
    'matchType': 'MatchType',
    'venue': 'MatchVenue',
    'date': 'MatchDate',
    'dateTimeGMT': 'MatchDateTime',
    'matchStarted': 'MatchStarted',
    'matchEnded': 'MatchEnded'
}, inplace=True)

In [81]:
match_list.columns.to_list()

['MatchID',
 'MatchName',
 'MatchType',
 'MatchVenue',
 'MatchDate',
 'MatchDateTime',
 'MatchStarted',
 'MatchEnded',
 'MatchNumber']

In [82]:
# Rearranging Columns

match_list = match_list[[
    'MatchID',
    'MatchName',
    'MatchNumber',
    'MatchType',
    'MatchVenue',
    'MatchDate',
    'MatchDateTime',
    'MatchStarted',
    'MatchEnded'    
]]

In [83]:
match_list

,MatchID,MatchName,MatchNumber,MatchType,MatchVenue,MatchDate,MatchDateTime,MatchStarted,MatchEnded
0,208d68e5-3fab-4f3b-88e9-29ec4a02d3e2,Chennai Super Kings vs Mumbai Indians,3,t20,"MA Chidambaram Stadium, Chennai",2025-03-23,2025-03-23T14:00:00,True,True
1,83d70527-5fc4-4fad-8dd2-b88b385f379e,Gujarat Titans vs Punjab Kings,5,t20,"Narendra Modi Stadium, Ahmedabad",2025-03-25,2025-03-25T14:00:00,True,True
2,d5915da0-c08b-4122-bcb0-2c2e1e6e168a,Kolkata Knight Riders vs Sunrisers Hyderabad,15,t20,"Eden Gardens, Kolkata",2025-04-03,2025-04-03T14:00:00,True,True
3,0a5ebe67-67a3-41d2-bbc8-5fc94aef0529,Mumbai Indians vs Royal Challengers Bengaluru,20,t20,"Wankhede Stadium, Mumbai",2025-04-07,2025-04-07T14:00:00,True,True
4,56a88e0e-e844-41bd-ba65-3c905e36ba0d,Punjab Kings vs Chennai Super Kings,22,t20,Maharaja Yadavindra Singh International Cricke...,2025-04-08,2025-04-08T14:00:00,True,True
...,...,...,...,...,...,...,...,...,...
70,38f4d432-1349-4223-87ab-b1279c553754,Royal Challengers Bengaluru vs Punjab Kings,74,t20,"Narendra Modi Stadium, Ahmedabad",2025-06-03,2025-06-03T14:00:00,True,True
71,5dc7a22f-5057-4895-bb98-965d9a1f004e,Lucknow Super Giants vs Mumbai Indians,16,t20,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,2025-04-04,2025-04-04T14:00:00,True,True
72,71213f27-c274-48b0-97f7-ec74e895dcbe,Gujarat Titans vs Rajasthan Royals,23,t20,"Narendra Modi Stadium, Ahmedabad",2025-04-09,2025-04-09T14:00:00,True,True
73,ab4e0813-1e78-467e-aca0-d80c5cfe7dbd,Sunrisers Hyderabad vs Lucknow Super Giants,7,t20,"Rajiv Gandhi International Stadium, Hyderabad",2025-03-27,2025-03-27T14:00:00,True,True
74,7431523f-7ccb-4a4a-aed7-5c42fc08464c,Chennai Super Kings vs Royal Challengers Benga...,8,t20,"MA Chidambaram Stadium, Chennai",2025-03-28,2025-03-28T14:00:00,True,True

##### Checking for Data Types

In [84]:
match_list.dtypes

MatchID          object
MatchName        object
MatchNumber       int64
MatchType        object
MatchVenue       object
MatchDate        object
MatchDateTime    object
MatchStarted       bool
MatchEnded         bool
dtype: object

In [85]:
match_list.MatchDate = match_list.MatchDate.astype('datetime64[D]')
match_list.MatchDateTime = match_list.MatchDateTime.astype('datetime64[h]')

##### Validating Data

In [89]:
check1 = match_list.sort_values(by='MatchNumber')
check2 = match_list.sort_values(by='MatchDateTime')

In [90]:
check1.equals(check2)

True

In [93]:
match_list.sort_values(by='MatchNumber', inplace=True)
match_list.reset_index(drop=True, inplace=True)

In [94]:
match_list

,MatchID,MatchName,MatchNumber,MatchType,MatchVenue,MatchDate,MatchDateTime,MatchStarted,MatchEnded
0,cacf2d34-41b8-41dd-91ed-5183d880084c,Kolkata Knight Riders vs Royal Challengers Ben...,1,t20,"Eden Gardens, Kolkata",2025-03-22,2025-03-22 14:00:00,True,True
1,91b007f3-c0af-493f-808a-3f4ae2d66e33,Sunrisers Hyderabad vs Rajasthan Royals,2,t20,"Rajiv Gandhi International Stadium, Hyderabad",2025-03-23,2025-03-23 10:00:00,True,True
2,208d68e5-3fab-4f3b-88e9-29ec4a02d3e2,Chennai Super Kings vs Mumbai Indians,3,t20,"MA Chidambaram Stadium, Chennai",2025-03-23,2025-03-23 14:00:00,True,True
3,c6e97609-d9c1-46eb-805a-e282b34f3bb1,Delhi Capitals vs Lucknow Super Giants,4,t20,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,2025-03-24,2025-03-24 14:00:00,True,True
4,83d70527-5fc4-4fad-8dd2-b88b385f379e,Gujarat Titans vs Punjab Kings,5,t20,"Narendra Modi Stadium, Ahmedabad",2025-03-25,2025-03-25 14:00:00,True,True
...,...,...,...,...,...,...,...,...,...
69,6f407b82-f31f-4e4e-bf65-763919972804,Lucknow Super Giants vs Royal Challengers Beng...,70,t20,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,2025-05-27,2025-05-27 14:00:00,True,True
70,bc3351d1-f950-4aa6-bb6f-473517a06885,Punjab Kings vs Royal Challengers Bengaluru,71,t20,Maharaja Yadavindra Singh International Cricke...,2025-05-29,2025-05-29 14:00:00,True,True
71,21cf482e-bb64-4b40-b6e0-6b51c77ba464,Gujarat Titans vs Mumbai Indians,72,t20,Maharaja Yadavindra Singh International Cricke...,2025-05-30,2025-05-30 14:00:00,True,True
72,c8425e58-85a4-4e8e-a56c-8afae638effb,Punjab Kings vs Mumbai Indians,73,t20,"Narendra Modi Stadium, Ahmedabad",2025-06-01,2025-06-01 14:00:00,True,True
73,38f4d432-1349-4223-87ab-b1279c553754,Royal Challengers Bengaluru vs Punjab Kings,74,t20,"Narendra Modi Stadium, Ahmedabad",2025-06-03,2025-06-03 14:00:00,True,True

#### Exporting Data to '.csv'

In [95]:
match_list.to_csv('match_list-9jun25.csv')

### Match Info

##### Creating a Custom DataFrame

In [33]:
info = pd.DataFrame(columns=['id', 'Team1', 'Team2', 'tossWinner', 'tossChoice', 'matchWinner', 'Innings1', 'r1', 'w1', 'o1', 'Innings2', 'r2', 'w2', 'o2'])

#### Fetching 'info' for each Match

In [101]:
for i in match_list.MatchID:
    URL = "https://api.cricapi.com/v1/match_info"
    APIKey = os.environ['APIKey']
    OFFSET = "0"
    MATCHId = str(i)
    queryRequest = URL + "?apikey=" + APIKey + "&offset=" + OFFSET + "&id=" + MATCHId
    print(MATCHId)

    # Checking Response Code
    match_info_response = requests.get(queryRequest)

    # Loading Data
    match_data = json.loads(match_info_response.text)

    info = info.append({
        'id': match_data['data']['id'],
        'Team1': match_data['data']['teams'][0],
        'Team2': match_data['data']['teams'][1],
        'tossWinner': match_data['data']['tossWinner'],
        'tossChoice': match_data['data']['tossChoice'],
        'matchWinner': match_data['data']['matchWinner'],
        'Innings1': match_data['data']['score'][0]['inning'],
        'r1': match_data['data']['score'][0]['r'],
        'w1': match_data['data']['score'][0]['w'],
        'o1': match_data['data']['score'][0]['o'],
        'Innings2': match_data['data']['score'][1]['inning'],
        'r2': match_data['data']['score'][1]['r'],
        'w2': match_data['data']['score'][1]['w'],
        'o2': match_data['data']['score'][1]['o']
    }, ignore_index=True)

cacf2d34-41b8-41dd-91ed-5183d880084c
91b007f3-c0af-493f-808a-3f4ae2d66e33
208d68e5-3fab-4f3b-88e9-29ec4a02d3e2
c6e97609-d9c1-46eb-805a-e282b34f3bb1
83d70527-5fc4-4fad-8dd2-b88b385f379e
fd459f45-6e79-42c5-84e4-d046f291cacf
ab4e0813-1e78-467e-aca0-d80c5cfe7dbd
7431523f-7ccb-4a4a-aed7-5c42fc08464c
f5ed540f-15c7-4189-a5d4-e54be746a522
af5cf1dd-b3d4-4e8d-8660-e5e27cd5202e
057ce3fb-8117-47fe-bf25-be0ed8a56dd0
075649ef-6ca8-4f50-8143-87814b828ea0
7896feec-8fd6-44ef-aee3-eabb679e6305
64e88ffc-606f-4d4f-b848-310f1ec7a98a
d5915da0-c08b-4122-bcb0-2c2e1e6e168a
5dc7a22f-5057-4895-bb98-965d9a1f004e
f5dabb5b-a934-4666-a368-7134e991f569
b2e603ab-96f7-4711-ac9f-6a78e742237d
3027ad1a-e7d8-4891-8ea0-1a56f81e8700
0a5ebe67-67a3-41d2-bbc8-5fc94aef0529
2ac97990-6265-40e4-b93e-fcd24e89026c
56a88e0e-e844-41bd-ba65-3c905e36ba0d
71213f27-c274-48b0-97f7-ec74e895dcbe
3f309c2d-75dd-48bc-9d9f-e3979e252949
b39bbd39-c67f-4892-9a48-02e958946718
35938151-73ee-4969-8153-db8aabee3b90
b13f129b-2596-429d-ad49-a1b0d102809b
953420f4-982c-4dcb-b8f7-bbda5acd438d
99c52578-1257-4834-9848-88cfec556836
263c1103-33c0-4c05-864f-5dbcd29ead9b
23f60d1b-2641-4a84-bb73-54d3aadfb294
3659022a-de1d-48fe-b68a-c62197297408
71756de6-bdef-4b23-801f-c6bec9604e07
ebce77ae-63e1-46eb-8ff4-360ba8dc9bf2
71666b6c-a6f9-4e09-a9d9-7f3ddca832d6
a007a070-6120-4e37-8bf9-c9582801a20b
4ace6d56-2e54-473e-a3c1-8bfcd06da6e2
01244c3f-ce16-42a7-bcee-31d75fcdfb4e
a62d133e-9370-4575-b649-9415fea63aab
47fd62f1-ca48-4c9c-9ded-0d2fcb5a64df
cec210ca-9184-43d3-9664-5ff0cbce7cd0
9c1e5e4c-b72e-4db2-b2be-df9b4d27f539
92d38459-52b6-40a9-8508-f3dd2692a0bf
3683354f-3c17-4346-9236-8d2bc474e7a5
eae7163d-b06c-41df-95fb-835fd5b9798b
04e8d307-7acd-4c3d-8117-b92ced6c583a
32450f41-24d3-463a-9d37-e6df114b43df
fa06c479-3015-4e58-b37c-9c6c076fab14
9b3be8ba-8302-4051-87a8-9022037b9a84
d0b375d6-eb90-48f9-b8a3-37647a418ea2
1a4b354c-8692-44d0-9b52-562da45bcce9
48e77e32-3016-4f17-9c99-a5663c5eb3e6
aeb65c00-9359-4bc0-827a-9d0365364d1b
df44cff0-d889-44a2-a63c-415c93b9d022
4e4b259f-19b6-4405-9df7-b94ce3b0a2c9

IndexError: list index out of range

##### Resolving and manually adding data for Match Number 55

In [105]:
match_list.loc[54]

MatchID                   4e4b259f-19b6-4405-9df7-b94ce3b0a2c9
MatchName                Sunrisers Hyderabad vs Delhi Capitals
MatchNumber                                                 55
MatchType                                                  t20
MatchVenue       Rajiv Gandhi International Stadium, Hyderabad
MatchDate                                  2025-05-05 00:00:00
MatchDateTime                              2025-05-05 14:00:00
MatchStarted                                              True
MatchEnded                                                True
Name: 54, dtype: object

In [110]:
URL = "https://api.cricapi.com/v1/match_info"
APIKey = os.environ['APIKey']
OFFSET = "0"
MATCHId = "4e4b259f-19b6-4405-9df7-b94ce3b0a2c9"
queryRequest = URL + "?apikey=" + APIKey + "&offset=" + OFFSET + "&id=" + MATCHId
print(MATCHId)

# Checking Response Code
match_info_response = requests.get(queryRequest)

# Loading Data
match_data = json.loads(match_info_response.text)
match_data

4e4b259f-19b6-4405-9df7-b94ce3b0a2c9

{'apikey': '5eed364a-ff6b-428b-a536-53d1e72b6131',
 'data': {'id': '4e4b259f-19b6-4405-9df7-b94ce3b0a2c9',
  'name': 'Sunrisers Hyderabad vs Delhi Capitals, 55th Match',
  'matchType': 't20',
  'status': 'No Result - due to rain',
  'venue': 'Rajiv Gandhi International Stadium, Hyderabad',
  'date': '2025-05-05',
  'dateTimeGMT': '2025-05-05T14:00:00',
  'teams': ['Sunrisers Hyderabad', 'Delhi Capitals'],
  'teamInfo': [{'name': 'Delhi Capitals',
    'shortname': 'DC',
    'img': 'https://g.cricapi.com/iapi/148-637874596301457910.png?w=48'},
   {'name': 'Sunrisers Hyderabad',
    'shortname': 'SRH',
    'img': 'https://g.cricapi.com/iapi/279-637852957609490368.png?w=48'}],
  'score': [{'r': 133, 'w': 7, 'o': 20, 'inning': 'Delhi Capitals Inning 1'}],
  'tossWinner': 'Sunrisers Hyderabad',
  'tossChoice': 'bowl',
  'matchWinner': 'No Winner',
  'series_id': 'd5a498c8-7596-4b93-8ab0-e0efc3345312',
  'fantasyEnabled': True,
  'bbbEnabled': True,
  'hasSquad': True,
  'matchStarted': True,
  'matchEnded': True},
 'status': 'success',
 'info': {'hitsToday': 56,
  'hitsUsed': 1,
  'hitsLimit': 100,
  'credits': 0,
  'server': 11,
  'queryTime': 26.5962,
  's': 0,
  'cache': 0}}

In [113]:
info = info.append({
    'id': match_data['data']['id'],
    'Team1': match_data['data']['teams'][0],
    'Team2': match_data['data']['teams'][1],
    'tossWinner': match_data['data']['tossWinner'],
    'tossChoice': match_data['data']['tossChoice'],
    'matchWinner': match_data['data']['matchWinner'],
    'Innings1': match_data['data']['score'][0]['inning'],
    'r1': match_data['data']['score'][0]['r'],
    'w1': match_data['data']['score'][0]['w'],
    'o1': match_data['data']['score'][0]['o'],
    'Innings2': np.nan,
    'r2': np.nan,
    'w2': np.nan,
    'o2': np.nan
}, ignore_index=True)

In [116]:
for i in match_list.MatchID[55:57]:
    URL = "https://api.cricapi.com/v1/match_info"
    APIKey = os.environ['APIKey']
    OFFSET = "0"
    MATCHId = str(i)
    queryRequest = URL + "?apikey=" + APIKey + "&offset=" + OFFSET + "&id=" + MATCHId
    print(MATCHId)

    # Checking Response Code
    match_info_response = requests.get(queryRequest)

    # Loading Data
    match_data = json.loads(match_info_response.text)

    info = info.append({
        'id': match_data['data']['id'],
        'Team1': match_data['data']['teams'][0],
        'Team2': match_data['data']['teams'][1],
        'tossWinner': match_data['data']['tossWinner'],
        'tossChoice': match_data['data']['tossChoice'],
        'matchWinner': match_data['data']['matchWinner'],
        'Innings1': match_data['data']['score'][0]['inning'],
        'r1': match_data['data']['score'][0]['r'],
        'w1': match_data['data']['score'][0]['w'],
        'o1': match_data['data']['score'][0]['o'],
        'Innings2': match_data['data']['score'][1]['inning'],
        'r2': match_data['data']['score'][1]['r'],
        'w2': match_data['data']['score'][1]['w'],
        'o2': match_data['data']['score'][1]['o']
    }, ignore_index=True)

a97077e7-466a-46e8-b6e7-2b74731b1d42
96324bfb-686e-44b6-a48e-5bd71188d1b2

##### Resolving and manually adding data for Match Number 58

In [117]:
match_list.loc[57]

MatchID                       bceb4ff2-269d-47d3-a59d-211f18f59e59
MatchName        Royal Challengers Bengaluru vs Kolkata Knight ...
MatchNumber                                                     58
MatchType                                                      t20
MatchVenue                        M.Chinnaswamy Stadium, Bengaluru
MatchDate                                      2025-05-17 00:00:00
MatchDateTime                                  2025-05-17 14:00:00
MatchStarted                                                  True
MatchEnded                                                    True
Name: 57, dtype: object

In [118]:
URL = "https://api.cricapi.com/v1/match_info"
APIKey = os.environ['APIKey']
OFFSET = "0"
MATCHId = "bceb4ff2-269d-47d3-a59d-211f18f59e59"
queryRequest = URL + "?apikey=" + APIKey + "&offset=" + OFFSET + "&id=" + MATCHId
print(MATCHId)

# Checking Response Code
match_info_response = requests.get(queryRequest)

# Loading Data
match_data = json.loads(match_info_response.text)
match_data

bceb4ff2-269d-47d3-a59d-211f18f59e59

{'apikey': '5eed364a-ff6b-428b-a536-53d1e72b6131',
 'data': {'id': 'bceb4ff2-269d-47d3-a59d-211f18f59e59',
  'name': 'Royal Challengers Bengaluru vs Kolkata Knight Riders, 58th Match',
  'matchType': 't20',
  'status': 'There is no scorecard available for this match.',
  'venue': 'M.Chinnaswamy Stadium, Bengaluru',
  'date': '2025-05-17',
  'dateTimeGMT': '2025-05-17T14:00:00',
  'teams': ['Royal Challengers Bengaluru', 'Kolkata Knight Riders'],
  'teamInfo': [{'name': 'Kolkata Knight Riders',
    'shortname': 'KKR',
    'img': 'https://g.cricapi.com/iapi/206-637852958714346149.png?w=48'},
   {'name': 'Royal Challengers Bengaluru',
    'shortname': 'RCB',
    'img': 'https://g.cricapi.com/iapi/21439-638468478038395955.jpg?w=48'}],
  'matchWinner': 'No Winner',
  'series_id': 'd5a498c8-7596-4b93-8ab0-e0efc3345312',
  'fantasyEnabled': False,
  'bbbEnabled': False,
  'hasSquad': True,
  'matchStarted': True,
  'matchEnded': True},
 'status': 'success',
 'info': {'hitsToday': 59,
  'hitsUsed': 1,
  'hitsLimit': 100,
  'credits': 0,
  'server': 1,
  'queryTime': 15.8347,
  's': 0,
  'cache': 0}}

In [119]:
info = info.append({
    'id': match_data['data']['id'],
    'Team1': match_data['data']['teams'][0],
    'Team2': match_data['data']['teams'][1],
    'tossWinner': np.nan,
    'tossChoice': np.nan,
    'matchWinner': match_data['data']['matchWinner'],
    'Innings1': np.nan,
    'r1': np.nan,
    'w1': np.nan,
    'o1': np.nan,
    'Innings2': np.nan,
    'r2': np.nan,
    'w2': np.nan,
    'o2': np.nan
}, ignore_index=True)

In [121]:
for i in match_list.MatchID[58:]:
    URL = "https://api.cricapi.com/v1/match_info"
    APIKey = os.environ['APIKey']
    OFFSET = "0"
    MATCHId = str(i)
    queryRequest = URL + "?apikey=" + APIKey + "&offset=" + OFFSET + "&id=" + MATCHId
    print(MATCHId)

    # Checking Response Code
    match_info_response = requests.get(queryRequest)

    # Loading Data
    match_data = json.loads(match_info_response.text)

    info = info.append({
        'id': match_data['data']['id'],
        'Team1': match_data['data']['teams'][0],
        'Team2': match_data['data']['teams'][1],
        'tossWinner': match_data['data']['tossWinner'],
        'tossChoice': match_data['data']['tossChoice'],
        'matchWinner': match_data['data']['matchWinner'],
        'Innings1': match_data['data']['score'][0]['inning'],
        'r1': match_data['data']['score'][0]['r'],
        'w1': match_data['data']['score'][0]['w'],
        'o1': match_data['data']['score'][0]['o'],
        'Innings2': match_data['data']['score'][1]['inning'],
        'r2': match_data['data']['score'][1]['r'],
        'w2': match_data['data']['score'][1]['w'],
        'o2': match_data['data']['score'][1]['o']
    }, ignore_index=True)

ac58e81f-a8b1-48e9-b7a1-9990b1bb24c3
481f7248-302b-4aa4-9af8-45fd85afdf83
37ffb02f-3858-4afd-8229-62f18f88693f
347e27a7-5e40-428f-8afb-adfae1d5d3dd
a4109c61-bed5-47fd-badd-f7e1e1291b82
513ef018-fd16-4fe6-b6d6-d84631e810b9
20aacd15-ede1-4447-9b21-dd08e51900b2
d14c8675-b2c6-4f20-920c-d44cc8d60fe7
f16e5b1e-1437-475b-8e8c-07d1d736f8a7
17f1c3f0-1ed8-4d84-8b8f-6a3e3357f47b
2207d377-6fe1-4197-9fb1-744e48c7e2d1
6f407b82-f31f-4e4e-bf65-763919972804
bc3351d1-f950-4aa6-bb6f-473517a06885
21cf482e-bb64-4b40-b6e0-6b51c77ba464
c8425e58-85a4-4e8e-a56c-8afae638effb
38f4d432-1349-4223-87ab-b1279c553754

#### Exporting data to '.csv'

In [123]:
info.to_csv('match_info-10jun25.csv')

## Scorecards

In [150]:
for i in match_list.MatchID[54:56]:
    URL = "https://api.cricapi.com/v1/match_scorecard"
    APIKey = os.environ['APIKey']
    OFFSET = "0"
    MATCHId = str(i)
    queryRequest = URL + "?apikey=" + APIKey + "&offset=" + OFFSET + "&id=" + MATCHId

    # Checking Response Code
    scorecard_response = requests.get(queryRequest)
    
    # Loading Data
    scorecard = json.loads(scorecard_response.text)

    # Saving Data
    with open(f'scorecard\{MATCHId}.json', 'w') as f:
        json.dump(scorecard['data']['scorecard'], f)

In [155]:
json.loads(scorecard_response.text)['info']

{'hitsToday': 95,
 'hitsUsed': 10,
 'hitsLimit': 100,
 'credits': 0,
 'server': 10,
 'queryTime': 26.5502,
 's': 0,
 'cache': 0}

In [158]:
for i in match_list.MatchID[59:66]:
    URL = "https://api.cricapi.com/v1/match_scorecard"
    APIKey = os.environ['APIKey']
    OFFSET = "0"
    MATCHId = str(i)
    queryRequest = URL + "?apikey=" + APIKey + "&offset=" + OFFSET + "&id=" + MATCHId

    # Checking Response Code
    scorecard_response = requests.get(queryRequest)
    
    # Loading Data
    scorecard = json.loads(scorecard_response.text)

    # Saving Data
    with open(f'scorecard\{MATCHId}.json', 'w') as f:
        json.dump(scorecard['data']['scorecard'], f)

In [159]:
json.loads(scorecard_response.text)['info']

{'hitsToday': 90,
 'hitsUsed': 10,
 'hitsLimit': 100,
 'credits': 0,
 'server': 12,
 'queryTime': 25.5373,
 's': 0,
 'cache': 0}

In [4]:
for i in match_list.MatchID[66:75]:
    URL = "https://api.cricapi.com/v1/match_scorecard"
    APIKey = os.environ['APIKey']
    OFFSET = "0"
    MATCHId = str(i)
    queryRequest = URL + "?apikey=" + APIKey + "&offset=" + OFFSET + "&id=" + MATCHId

    # Checking Response Code
    scorecard_response = requests.get(queryRequest)
    
    # Loading Data
    scorecard = json.loads(scorecard_response.text)

    # Saving Data
    with open(f'scorecard\{MATCHId}.json', 'w') as f:
        json.dump(scorecard['data']['scorecard'], f)

In [5]:
json.loads(scorecard_response.text)['info']

{'hitsToday': 80,
 'hitsUsed': 10,
 'hitsLimit': 100,
 'credits': 0,
 'server': 5,
 'queryTime': 26.3035,
 's': 0,
 'cache': 0}

#### Checking for missing files

In [30]:
for i in match_list.MatchID:
    with open(f'scorecard/{i}.json', 'r') as f:
        filedata = json.load(f)
    print(match_list.MatchName.loc[match_list.MatchID == i])

0    Kolkata Knight Riders vs Royal Challengers Ben...
Name: MatchName, dtype: object
1    Sunrisers Hyderabad vs Rajasthan Royals
Name: MatchName, dtype: object
2    Chennai Super Kings vs Mumbai Indians
Name: MatchName, dtype: object
3    Delhi Capitals vs Lucknow Super Giants
Name: MatchName, dtype: object
4    Gujarat Titans vs Punjab Kings
Name: MatchName, dtype: object
5    Rajasthan Royals vs Kolkata Knight Riders
Name: MatchName, dtype: object
6    Sunrisers Hyderabad vs Lucknow Super Giants
Name: MatchName, dtype: object
7    Chennai Super Kings vs Royal Challengers Benga...
Name: MatchName, dtype: object
8    Gujarat Titans vs Mumbai Indians
Name: MatchName, dtype: object
9    Delhi Capitals vs Sunrisers Hyderabad
Name: MatchName, dtype: object
10    Rajasthan Royals vs Chennai Super Kings
Name: MatchName, dtype: object
11    Mumbai Indians vs Kolkata Knight Riders
Name: MatchName, dtype: object
12    Lucknow Super Giants vs Punjab Kings
Name: MatchName, dtype: object
13    Royal Challengers Bengaluru vs Gujarat Titans
Name: MatchName, dtype: object
14    Kolkata Knight Riders vs Sunrisers Hyderabad
Name: MatchName, dtype: object
15    Lucknow Super Giants vs Mumbai Indians
Name: MatchName, dtype: object
16    Chennai Super Kings vs Delhi Capitals
Name: MatchName, dtype: object
17    Punjab Kings vs Rajasthan Royals
Name: MatchName, dtype: object
18    Sunrisers Hyderabad vs Gujarat Titans
Name: MatchName, dtype: object
19    Mumbai Indians vs Royal Challengers Bengaluru
Name: MatchName, dtype: object
20    Kolkata Knight Riders vs Lucknow Super Giants
Name: MatchName, dtype: object
21    Punjab Kings vs Chennai Super Kings
Name: MatchName, dtype: object
22    Gujarat Titans vs Rajasthan Royals
Name: MatchName, dtype: object
23    Royal Challengers Bengaluru vs Delhi Capitals
Name: MatchName, dtype: object
24    Chennai Super Kings vs Kolkata Knight Riders
Name: MatchName, dtype: object
25    Lucknow Super Giants vs Gujarat Titans
Name: MatchName, dtype: object
26    Sunrisers Hyderabad vs Punjab Kings
Name: MatchName, dtype: object
27    Rajasthan Royals vs Royal Challengers Bengaluru
Name: MatchName, dtype: object
28    Delhi Capitals vs Mumbai Indians
Name: MatchName, dtype: object
29    Lucknow Super Giants vs Chennai Super Kings
Name: MatchName, dtype: object
30    Punjab Kings vs Kolkata Knight Riders
Name: MatchName, dtype: object
31    Delhi Capitals vs Rajasthan Royals
Name: MatchName, dtype: object
32    Mumbai Indians vs Sunrisers Hyderabad
Name: MatchName, dtype: object
33    Royal Challengers Bengaluru vs Punjab Kings
Name: MatchName, dtype: object
34    Gujarat Titans vs Delhi Capitals
Name: MatchName, dtype: object
35    Rajasthan Royals vs Lucknow Super Giants
Name: MatchName, dtype: object
36    Punjab Kings vs Royal Challengers Bengaluru
Name: MatchName, dtype: object
37    Mumbai Indians vs Chennai Super Kings
Name: MatchName, dtype: object
38    Kolkata Knight Riders vs Gujarat Titans
Name: MatchName, dtype: object
39    Lucknow Super Giants vs Delhi Capitals
Name: MatchName, dtype: object
40    Sunrisers Hyderabad vs Mumbai Indians
Name: MatchName, dtype: object
41    Royal Challengers Bengaluru vs Rajasthan Royals
Name: MatchName, dtype: object
42    Chennai Super Kings vs Sunrisers Hyderabad
Name: MatchName, dtype: object
43    Kolkata Knight Riders vs Punjab Kings
Name: MatchName, dtype: object
44    Mumbai Indians vs Lucknow Super Giants
Name: MatchName, dtype: object
45    Delhi Capitals vs Royal Challengers Bengaluru
Name: MatchName, dtype: object
46    Rajasthan Royals vs Gujarat Titans
Name: MatchName, dtype: object
47    Delhi Capitals vs Kolkata Knight Riders
Name: MatchName, dtype: object
48    Chennai Super Kings vs Punjab Kings
Name: MatchName, dtype: object
49    Rajasthan Royals vs Mumbai Indians
Name: MatchName, dtype: object
50    Gujarat Titans vs Sunrisers Hyderabad
Name: MatchName, dtype: object
51    Royal Challengers Bengaluru vs Chennai Super K...
Name: MatchName, dtype: object
52    Kolkata Knight Riders vs Rajasthan Royals
Name: MatchName, dtype: object

FileNotFoundError: [Errno 2] No such file or directory: 'scorecard/df44cff0-d889-44a2-a63c-415c93b9d022.json'

#### Manually fetching the missing file

In [31]:
URL = "https://api.cricapi.com/v1/match_scorecard"
APIKey = os.environ['APIKey']
OFFSET = "0"
MATCHId = "df44cff0-d889-44a2-a63c-415c93b9d022"
queryRequest = URL + "?apikey=" + APIKey + "&offset=" + OFFSET + "&id=" + MATCHId

# Checking Response Code
scorecard_response = requests.get(queryRequest)

# Loading Data
scorecard = json.loads(scorecard_response.text)

# Saving Data
with open(f'scorecard\{MATCHId}.json', 'w') as f:
    json.dump(scorecard['data']['scorecard'], f)

In [32]:
json.loads(scorecard_response.text)['info']

{'hitsToday': 90,
 'hitsUsed': 10,
 'hitsLimit': 100,
 'credits': 0,
 'server': 5,
 'queryTime': 29.1316,
 's': 0,
 'cache': 0}